name: CI

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:

jobs:
  validate_schemas:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r tests/test_requirements.txt
        pip list

    - name: Test with pytest
      run: |
        python -m pytest tests
